<?php
/**
 *  Drimple
 *  Copyright (C) 2012  Korstiaan de Ridder <korstiaan [at] korstiaan.com>
 *
 *	This file is part of Drimple
 *
 *  Drimple is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Drimple is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Drimple.  If not, see <http://www.gnu.org/licenses/>.
 */

function drimple_init()
{
	if (!class_exists('\Drimple\Drimple')) {
		require __DIR__.'/Drimple/Drimple.php';
		require __DIR__.'/Drimple/Provider/ServiceProviderInterface.php';	
	}
	module_invoke_all('drimple_provide', \Drimple\Drimple::getInstance());
}