<?php

/**
 * This file is part of Drimple
 *
 * (c) Korstiaan de Ridder <korstiaan@korstiaan.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

/**
 * @return \Drimple\Drimple
 */
function drimple()
{
	static $drimple = null;
	if (null === $drimple) {
		if (!class_exists('\Drimple\Drimple')) {
			require __DIR__.'/src/Drimple/Drimple.php';
			require __DIR__.'/src/Drimple/Provider/ServiceProviderInterface.php';	
		}
		$drimple = new \Drimple\Drimple();
		module_invoke_all('drimple_provide', $drimple);
	}
	return $drimple;
}